# Note: The top-level "version" attribute has been removed as it is obsolete.
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: frankie_backend
    env_file:
      - ./backend/.env
    extra_hosts: # <-- ADD THIS BLOCK
      - "host.docker.internal:host-gateway" # <--
    volumes:
      # This mounts your local backend code directly into the container's app directory.
      # It ensures any code changes you make are immediately available to the running server.
      - ./backend:/app
      
      # The existing volumes are still needed:
      - ./:/frankie_codebase
      - ./config/config.yml:/app/config/config.yml:ro
      - frankie_data:/app/data
    networks:
      - frankie_net
    restart: unless-stopped
    # The CMD command is defined in the backend/Dockerfile.

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frankie_frontend
    networks:
      - frankie_net
    restart: unless-stopped

  proxy:
    image: caddy:2-alpine
    container_name: frankie_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frankie_net
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

volumes:
  frankie_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  frankie_net:
    driver: bridge

