version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: frankie_backend
    volumes:
      - ./:/app
      - ./config/config.yml:/app/config/config.yml:ro
      - ./backend/data:/app/backend/data
      - ./logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    networks:
      - frankie_net
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: frankie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: frankie
      POSTGRES_PASSWORD: frankiepass
      POSTGRES_DB: frankiedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frankie_net

  ollama:
    image: ollama/ollama
    container_name: frankie_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - frankie_net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frankie_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frankie_net
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:

networks:
  frankie_net:
    driver: bridge