"""Initial database schema

Revision ID: efee5e6249f6
Revises: 
Create Date: 2025-06-17 13:27:20.392128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efee5e6249f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_permissions_id'), 'agent_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_permissions_path'), 'agent_permissions', ['path'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('genealogy_family_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genealogy_family_trees_id'), 'genealogy_family_trees', ['id'], unique=False)
    op.create_table('genealogy_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('death_date', sa.String(), nullable=True),
    sa.Column('death_place', sa.String(), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['genealogy_family_trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genealogy_persons_gedcom_id'), 'genealogy_persons', ['gedcom_id'], unique=False)
    op.create_index(op.f('ix_genealogy_persons_id'), 'genealogy_persons', ['id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('plugin_id', sa.String(), nullable=False),
    sa.Column('target_files', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PLANNING', 'ANALYZING', 'TESTING', 'AWAITING_REVIEW', 'EXECUTING_MILESTONE', 'APPLIED', 'REJECTED', 'ERROR', name='task_status_enum_v4'), nullable=False),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('proposed_diff', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('test_status', sa.Enum('NOT_RUN', 'PASS', 'FAIL', name='test_status_enum_v4'), nullable=False),
    sa.Column('test_results', sa.Text(), nullable=True),
    sa.Column('target_tree_id', sa.Integer(), nullable=True),
    sa.Column('target_person_id', sa.Integer(), nullable=True),
    sa.Column('task_context_data', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['genealogy_persons.id'], ),
    sa.ForeignKeyConstraint(['target_tree_id'], ['genealogy_family_trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_table('genealogy_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gedcom_id', sa.String(), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('husband_id', sa.Integer(), nullable=True),
    sa.Column('wife_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['husband_id'], ['genealogy_persons.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['genealogy_family_trees.id'], ),
    sa.ForeignKeyConstraint(['wife_id'], ['genealogy_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genealogy_families_gedcom_id'), 'genealogy_families', ['gedcom_id'], unique=False)
    op.create_index(op.f('ix_genealogy_families_id'), 'genealogy_families', ['id'], unique=False)
    op.create_table('family_child_association',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['genealogy_families.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['genealogy_persons.id'], ),
    sa.PrimaryKeyConstraint('family_id', 'person_id')
    )
    op.create_table('genealogy_research_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('agent_task_id', sa.Integer(), nullable=False),
    sa.Column('data_field', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('suggested_value', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'ACCEPTED', 'REJECTED', name='finding_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['genealogy_persons.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genealogy_research_findings_id'), 'genealogy_research_findings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genealogy_research_findings_id'), table_name='genealogy_research_findings')
    op.drop_table('genealogy_research_findings')
    op.drop_table('family_child_association')
    op.drop_index(op.f('ix_genealogy_families_id'), table_name='genealogy_families')
    op.drop_index(op.f('ix_genealogy_families_gedcom_id'), table_name='genealogy_families')
    op.drop_table('genealogy_families')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_genealogy_persons_id'), table_name='genealogy_persons')
    op.drop_index(op.f('ix_genealogy_persons_gedcom_id'), table_name='genealogy_persons')
    op.drop_table('genealogy_persons')
    op.drop_index(op.f('ix_genealogy_family_trees_id'), table_name='genealogy_family_trees')
    op.drop_table('genealogy_family_trees')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agent_permissions_path'), table_name='agent_permissions')
    op.drop_index(op.f('ix_agent_permissions_id'), table_name='agent_permissions')
    op.drop_table('agent_permissions')
    # ### end Alembic commands ###
